//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stdblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogpost
    {
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public string content { get; set; }
        public byte[] postimage { get; set; }
    }
}
