//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stdblog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class studentDBase : DbContext
    {
        public studentDBase()
            : base("name=studentDBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public virtual DbSet<blogpost> blogposts { get; set; }
        public virtual DbSet<profileimg> profileimgs { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
    
        public virtual int addposts(string posttitle, string postauthor, Nullable<System.DateTime> datemodified, string postcontent, byte[] postimage)
        {
            var posttitleParameter = posttitle != null ?
                new ObjectParameter("posttitle", posttitle) :
                new ObjectParameter("posttitle", typeof(string));
    
            var postauthorParameter = postauthor != null ?
                new ObjectParameter("postauthor", postauthor) :
                new ObjectParameter("postauthor", typeof(string));
    
            var datemodifiedParameter = datemodified.HasValue ?
                new ObjectParameter("datemodified", datemodified) :
                new ObjectParameter("datemodified", typeof(System.DateTime));
    
            var postcontentParameter = postcontent != null ?
                new ObjectParameter("postcontent", postcontent) :
                new ObjectParameter("postcontent", typeof(string));
    
            var postimageParameter = postimage != null ?
                new ObjectParameter("postimage", postimage) :
                new ObjectParameter("postimage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addposts", posttitleParameter, postauthorParameter, datemodifiedParameter, postcontentParameter, postimageParameter);
        }
    
        public virtual int profilepic(string profile, string username)
        {
            var profileParameter = profile != null ?
                new ObjectParameter("profile", profile) :
                new ObjectParameter("profile", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("profilepic", profileParameter, usernameParameter);
        }
    
        public virtual ObjectResult<searchuser_Result> searchuser(string searchvalue)
        {
            var searchvalueParameter = searchvalue != null ?
                new ObjectParameter("searchvalue", searchvalue) :
                new ObjectParameter("searchvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchuser_Result>("searchuser", searchvalueParameter);
        }
    
        public virtual int StdProcedure(string fN, string lN, string uN, string email, string pass, string country)
        {
            var fNParameter = fN != null ?
                new ObjectParameter("FN", fN) :
                new ObjectParameter("FN", typeof(string));
    
            var lNParameter = lN != null ?
                new ObjectParameter("LN", lN) :
                new ObjectParameter("LN", typeof(string));
    
            var uNParameter = uN != null ?
                new ObjectParameter("UN", uN) :
                new ObjectParameter("UN", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StdProcedure", fNParameter, lNParameter, uNParameter, emailParameter, passParameter, countryParameter);
        }
    
        public virtual int updateimgprocedure(byte[] profilepic, string username)
        {
            var profilepicParameter = profilepic != null ?
                new ObjectParameter("profilepic", profilepic) :
                new ObjectParameter("profilepic", typeof(byte[]));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateimgprocedure", profilepicParameter, usernameParameter);
        }
    
        public virtual ObjectResult<byte[]> uploadprocedure(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("uploadprocedure", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> validator(string username, string userpassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpasswordParameter = userpassword != null ?
                new ObjectParameter("userpassword", userpassword) :
                new ObjectParameter("userpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("validator", usernameParameter, userpasswordParameter);
        }
    }
}
