//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stdblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profileimg
    {
        public int pictureid { get; set; }
        public string username { get; set; }
        public byte[] profilepic { get; set; }
    }
}
